![](Mu1.png)
**PAWAN KUMAR**

# Course_1

# Programming for Everybody (Getting Started with Python)
***by University of Michigan***

### Week_1 Chapter One - Why we Program?
No assignment

### Week_2 Installing and Using Python
No assignment

### Week_3 Chapter One: Why We Program (continued)
Assignment :- Write Hello World!


**Write a program that uses a print statement to say 'hello world'**


In [1]:
# the code below almost works
print("hello world")

hello world


### Week_4 Chapter Two: Variables and Expressions
Asignment_2.2

**2.2 Write a program that uses input to prompt a user for their name and then welcomes with Hello name**

In [2]:
name = input("Enter your name:")
print("Hello",name)

Enter your name:Chuck
Hello Chuck


Assignment_2.3

**2.3 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.**

In [3]:
# This first line is provided for you
hours = float(input("Enter Hours:"))
rate = float(input("Enter rate:"))
gross_pay = hours * rate
print("Pay:",gross_pay)

Enter Hours:35
Enter rate:2.75
Pay: 96.25


### Week_5 Chapter Three: Conditional Code
Assignment_3.1

**3.1 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.**

In [4]:
h = float(input("Enter Hours:"))
r = float(input("Enter  Rate:"))
if h < 0 or r < 0:
        print( "none")
elif h > 40:
        print (40 * r + (h - 40) * 1.5 * r)
else:
        print (h * r)


Enter Hours:45
Enter  Rate:10.50
498.75


Assignment_3.3

**3.3 Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:
Score Grade**
**>= 0.9 A**
**>= 0.8 B**
**>= 0.7 C**
**>= 0.6 D**
**< 0.6 F**
**If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.**

In [5]:
score = float(input("Enter Score: "))
if score < 0.0 or score > 1.0:
    print("error")

elif score >= 0.9:
    print("A")   
elif score >= 0.8:
    print("B")
elif score >= 0.7:
    print("C")
elif score >= 0.6:
    print("D") 
elif score < 0.6:
    print("Fail")

Enter Score: 0.85
B


### Week_6 Chapter Four: Functions
Assignment_4.6

**4.6 Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.**

In [6]:
def computepay(h,r):
    if h < 0 or r < 0:
        return none
    elif h > 40:
        return (h * r + (h - 40) *0.5 * r)
    else:
        return h *  r

h = float(input("Enter Hours:"))
r = float(input("Enter Rate"))
p = computepay(h,r)
print("Pay",p)

Enter Hours:45
Enter Rate10.50
Pay 498.75


### Week_7 Chapter Five: Loops and Iteration
Assignment_5.2

**5.2 Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.**

In [7]:
largest = None
smallest = None
while True:
    user_input = input("Enter a number: ")
    if user_input == "done" :
        break
    try:
        num = int(user_input)
        if smallest is None or num < smallest:
           smallest = num
        elif largest is None or num > largest:
             largest = num
    except:
        print("Invalid input")
        continue

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2


# END

**Check my Accomplishment** link:- https://www.coursera.org/account/accomplishments/verify/AZQZ2XDAHH72

**This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python.  The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”.  Once a student completes this course, they will be ready to take more advanced programming courses.**